/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#3b4b3d',
        surface: '#131318',
        'on-tertiary-fixed-variant': '#004e5f',
        'inverse-on-surface': '#303036',
        'tertiary-fixed': '#b4ebff',
        'inverse-primary': '#006d37',
        'surface-container-low': '#1b1b20',
        'surface-tint': '#00e479',
        'on-primary-container': '#007139',
        'secondary-container': '#fe00fe',
        'surface-variant': '#35343a',
        'on-tertiary-container': '#006b82',
        'on-tertiary': '#003642',
        'on-primary': '#003919',
        'on-primary-fixed-variant': '#005228',
        'on-tertiary-fixed': '#001f27',
        'tertiary-container': '#a7e8ff',
        'on-secondary-fixed': '#380038',
        'on-surface-variant': '#b9cbb9',
        outline: '#849585',
        'tertiary-fixed-dim': '#3cd7ff',
        tertiary: '#f6fcff',
        'surface-bright': '#39383e',
        'primary-container': '#00ff88',
        'on-secondary': '#5b005b',
        'surface-container-lowest': '#0e0e13',
        'on-surface': '#e4e1e9',
        'secondary-fixed': '#ffd7f5',
        primary: '#f1ffef',
        'primary-fixed-dim': '#00e479',
        'on-secondary-container': '#500050',
        'error-container': '#93000a',
        'inverse-surface': '#e4e1e9',
        'secondary-fixed-dim': '#ffabf3',
        'on-background': '#e4e1e9',
        'surface-container': '#1f1f25',
        'surface-dim': '#131318',
        'on-secondary-fixed-variant': '#810081',
        'surface-container-highest': '#35343a',
        'on-primary-fixed': '#00210c',
        secondary: '#ffabf3',
        error: '#ffb4ab',
        'on-error': '#690005',
        'primary-fixed': '#60ff99',
        'on-error-container': '#ffdad6',
        background: '#131318',
        'surface-container-high': '#2a292f',
      },
      fontFamily: {
        'body-lg': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'code-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'margin-desktop': '64px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '16px',
        unit: '4px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
